export { default as Home } from './Home';
export { default as FacebookPosts } from './FacebookPosts';
export { default as InstagramPosts } from './InstagramPosts';
export { default as Kanban } from './apps/Kanban';
export { default as Workflow } from './apps/Workflow';
export { default as Comments } from './Comments';
export { default as Scheduler } from './apps/Scheduler';
export { default as Statistics } from './Statistics';
export { default as LoginPage } from './Logare';
